In [1]:
import pandas as pd
import yaml
pd.options.display.max_columns = 99

In [2]:
df = pd.read_csv('../input/awards_1967-2017_2017-08.csv.gz')
df.columns

/Users/invinst/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (17,23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Index(['row_id', 'birth_year', 'gender', 'race', 'current_star',
       'appointed_date', 'rank', 'last_promotion_date', 'resignation_date',
       'pps_award_detail_id', 'award_type', 'award_request_date',
       'tracking_no', 'current_award_status', 'requester_full_name',
       'award_start_date', 'award_end_date', 'ceremony_date', 'first_name',
       'first_name_NS', 'last_name', 'last_name_NS', 'middle_initial',
       'middle_initial2', 'suffix_name', 'awards_1967-2017_2017-08_ID'],
      dtype='object')

In [46]:
keeplist = ['PO', 'P O', 'P.O', 'SERGEANT']
droplist = ['LEGAL', 'AIDE', 'CLERK', 'POL ', 'DIR',
            'SUPV', 'SUPT', 'MANAGER', 'TECH']
df['is_po'] =0 
df.loc[(df['rank'].str.startswith('9', 'UNK')) &
((df['rank'] == 'CHIEF') | (df['rank'] == 'DEP CHIEF')) |
((df['rank'].str.contains('|'.join(keeplist))) &
(~df['rank'].str.contains('|'.join(droplist)))), 'is_po'] = 1

In [3]:
df[df['rank'].str.contains("UNK")].sort_values("awards_1967-2017_2017-08_ID")

,row_id,birth_year,gender,race,current_star,appointed_date,rank,last_promotion_date,resignation_date,pps_award_detail_id,award_type,award_request_date,tracking_no,current_award_status,requester_full_name,award_start_date,award_end_date,ceremony_date,first_name,first_name_NS,last_name,last_name_NS,middle_initial,middle_initial2,suffix_name,awards_1967-2017_2017-08_ID
125461,125462,1925.0,MALE,WHITE,NaN,1953-09-23,UNK-UNKNOWN,NaN,1980-04-17,8111563,DEPARTMENT COMMENDATION,2016-12-03,HZ528135,DELETED,"LULE, JOSE",2016-11-27,2016-11-28,NaN,ABRAHAM,ABRAHAM,TROOP,TROOP,NaN,NaN,NaN,70
125460,125461,1925.0,MALE,WHITE,NaN,1953-09-23,UNK-UNKNOWN,NaN,1980-04-17,8099473,HONORABLE MENTION,2014-11-24,NaN,DELETED,"MEDINA, VICTOR",2014-11-23,2014-11-23,NaN,ABRAHAM,ABRAHAM,TROOP,TROOP,NaN,NaN,NaN,70
125459,125460,1925.0,MALE,WHITE,NaN,1953-09-23,UNK-UNKNOWN,NaN,1980-04-17,8098158,DEPARTMENT COMMENDATION,2014-09-04,HX409024,DELETED,"HAGEMANN, PAUL",2014-08-30,2014-08-30,NaN,ABRAHAM,ABRAHAM,TROOP,TROOP,NaN,NaN,NaN,70
125458,125459,1925.0,MALE,WHITE,NaN,1953-09-23,UNK-UNKNOWN,NaN,1980-04-17,8096076,HONORABLE MENTION,2014-06-13,HX301228,DELETED,"WALCZAK, TRACY",2014-06-12,2014-06-12,NaN,ABRAHAM,ABRAHAM,TROOP,TROOP,NaN,NaN,NaN,70
119759,119760,1943.0,FEMALE,WHITE,NaN,1978-01-01,UNK-UNKNOWN,1973-08-01,1988-01-01,8059307,HONORABLE MENTION,2009-10-15,HR573450,DELETED,"ANTHONY, GWANA",2009-10-06,2009-10-06,NaN,ALICE,ALICE,STREB,STREB,NaN,NaN,NaN,619
571282,571283,1924.0,MALE,HISPANIC,NaN,1960-09-12,UNK-UNKNOWN,1983-12-16,1987-12-02,8041518,COMPLIMENTARY LETTER,2008-09-22,NaN,FINAL,"LEWIS-HALL, KAREN",2008-04-15,2008-09-22,NaN,ANDREW,ANDREW,RODRIGUEZ,RODRIGUEZ,NaN,NaN,NaN,1045
126282,126283,NaN,MALE,WHITE,NaN,2002-09-04,UNK-UNKNOWN,NaN,NaN,8103996,DEPARTMENT COMMENDATION,2015-08-11,HY281914,DELETED,"COLLINS, TERRENCE",2015-05-31,2015-06-04,NaN,ARMANDO,ARMANDO,UGARTE,UGARTE,NaN,NaN,NaN,1903
126280,126281,NaN,MALE,WHITE,NaN,2002-09-04,UNK-UNKNOWN,NaN,NaN,8081979,TRAFFIC STOP OF THE MONTH AWARD,2012-05-23,HT277526,DELETED,"MC KENZIE, PATRICK",2011-05-03,2011-05-04,NaN,ARMANDO,ARMANDO,UGARTE,UGARTE,NaN,NaN,NaN,1903
126283,126284,NaN,MALE,WHITE,NaN,2002-09-04,UNK-UNKNOWN,NaN,NaN,8107754,DEPARTMENT COMMENDATION,2016-03-30,HZ200160,DELETED,"WOODS, ROBERT",2016-03-25,2016-03-25,NaN,ARMANDO,ARMANDO,UGARTE,UGARTE,NaN,NaN,NaN,1903
126278,126279,NaN,MALE,WHITE,NaN,2002-09-04,UNK-UNKNOWN,NaN,NaN,8059236,HONORABLE MENTION,2009-10-12,HR534353,DELETED,"LAPITAN, WILFREDO",2009-09-13,2009-09-13,NaN,ARMANDO,ARMANDO,UGARTE,UGARTE,NaN,NaN,NaN,1903
126279,126280,NaN,MALE,WHITE,NaN,2002-09-04,UNK-UNKNOWN,NaN,NaN,8067573,HONORABLE MENTION,2010-09-23,HS216864,DELETED,"BELTRAN, EDUARDO",2010-03-20,2010-03-20,NaN,ARMANDO,ARMANDO,UGARTE,UGARTE,NaN,NaN,NaN,1903
126284,126285,NaN,MALE,WHITE,NaN,2002-09-04,UNK-UNKNOWN,NaN,NaN,8114089,HONORABLE MENTION,2017-04-22,JA234242,DELETED,"SELLERS, KEVIN",2017-04-21,2017-04-22,NaN,ARMANDO,ARMANDO,UGARTE,UGARTE,NaN,NaN,NaN,1903
126285,126286,NaN,MALE,WHITE,NaN,2002-09-04,UNK-UNKNOWN,NaN,NaN,8114090,HONORABLE MENTION,2017-04-22,NaN,DELETED,"SELLERS, KEVIN",2017-04-21,2017-04-22,NaN,ARMANDO,ARMANDO,UGARTE,UGARTE,NaN,NaN,NaN,1903
126286,126287,NaN,MALE,WHITE,NaN,2002-09-04,UNK-UNKNOWN,NaN,NaN,8114932,HONORABLE MENTION,2017-06-11,JA299348,DELETED,"DENNIS, ARSHELL",2017-06-09,2017-06-09,NaN,ARMANDO,ARMANDO,UGARTE,UGARTE,NaN,NaN,NaN,1903
653693,653694,NaN,MALE,WHITE,NaN,2002-09-04,UNK-UNKNOWN,NaN,NaN,8104984,HONORABLE MENTION,2015-10-22,NaN,FINAL,"COLLINS, TERRENCE",2015-07-03,2015-07-06,NaN,ARMANDO,ARMANDO,UGARTE,UGARTE,NaN,NaN,NaN,1903
653692,653693,NaN,MALE,WHITE,NaN,2002-09-04,UNK-UNKNOWN,NaN,NaN,8068366,SUPERINTENDENTS AWARD OF MERIT,2010-10-31,HS269519,FINAL,"EVANS, GLENN",2010-04-21,2010-04-24,2015-02-27,ARMANDO,ARMANDO,UGARTE,UGARTE,NaN,NaN,NaN,1903
653691,653692,NaN,MALE,WHITE,NaN,2002-09-04,UNK-UNKNOWN,NaN,NaN,8053214,COMPLIMENTARY LETTER,2009-04-15,NaN,FINAL,"LEWIS-HALL, KAREN",2008-08-14,2008-08-14,NaN,ARMANDO,ARMANDO,UGARTE,UGARTE,NaN,NaN,NaN,1903
126281,126282,NaN,MALE,WHITE,NaN,2002-09-04,UNK-UNKNOWN,NaN,NaN,8091351,HONORABLE MENTION,2013-09-17,HW275490,DELETED,"BRADLEY, WILLIAM",2013-05-15,2013-05-15,NaN,ARMANDO,ARMANDO,UGARTE,UGARTE,NaN,NaN,NaN,1903
641982,641983,1924.0,MALE,BLACK,NaN,1954-06-16,UNK-UNKNOWN,1979-08-16,1987-04-16,8074569,COMPLIMENTARY LETTER,2011-06-13,NaN,FINAL,"HOOVER, TRACY",2009-06-19,NaN,NaN,ARTHUR,ARTHUR,THOMPSON,THOMPSON,R,NaN,NaN,2026
641983,641984,1924.0,MALE,BLACK,NaN,1954-06-16,UNK-UNKNOWN,1979-08-16,1987-04-16,8096793,COMPLIMENTARY LETTER,2014-07-16,NaN,FINAL,"JOHNSON, PRISCILLA",2014-03-10,NaN,NaN,ARTHUR,ARTHUR,THOMPSON,THOMPSON,R,NaN,NaN,2026
123405,123406,1924.0,MALE,BLACK,NaN,1954-06-16,UNK-UNKNOWN,1979-08-16,1987-04-16,8109682,HONORABLE MENTION,2016-08-04,HZ375480,DELETED,"SANTIAGO, TIFFANY",2016-08-02,2016-08-02,NaN,ARTHUR,ARTHUR,THOMPSON,THOMPSON,R,NaN,NaN,2026
641985,641986,1924.0,MALE,BLACK,NaN,1954-06-16,UNK-UNKNOWN,1979-08-16,1987-04-16,8112692,COMPLIMENTARY LETTER,2017-02-06,NaN,FINAL,"DUONG, JIM",2017-02-06,2017-02-06,NaN,ARTHUR,ARTHUR,THOMPSON,THOMPSON,R,NaN,NaN,2026
123402,123403,1924.0,MALE,BLACK,NaN,1954-06-16,UNK-UNKNOWN,1979-08-16,1987-04-16,8092488,HONORABLE MENTION,2013-11-14,HW304811,DELETED,"KOCHAN, MARK",2013-06-04,2013-06-04,NaN,ARTHUR,ARTHUR,THOMPSON,THOMPSON,R,NaN,NaN,2026
123403,123404,1924.0,MALE,BLACK,NaN,1954-06-16,UNK-UNKNOWN,1979-08-16,1987-04-16,8098707,HONORABLE MENTION,2014-10-09,HX459217,DELETED,"CAVANAUGH, MICHAEL",2014-10-07,2014-10-07,NaN,ARTHUR,ARTHUR,THOMPSON,THOMPSON,R,NaN,NaN,2026
123404,123405,1924.0,MALE,BLACK,NaN,1954-06-16,UNK-UNKNOWN,1979-08-16,1987-04-16,8099963,HONORABLE MENTION,2014-12-24,HX553388,DELETED,"RIGAN, KRISTOPHE",2014-12-23,2014-12-24,NaN,ARTHUR,ARTHUR,THOMPSON,THOMPSON,R,NaN,NaN,2026
641984,641985,1924.0,MALE,BLACK,NaN,1954-06-16,UNK-UNKNOWN,1979-08-16,1987-04-16,8110804,COMPLIMENTARY LETTER,2016-10-14,NaN,FINAL,"JOHNSON, PRISCILLA",2016-08-27,NaN,NaN,ARTHUR,ARTHUR,THOMPSON,THOMPSON,R,NaN,NaN,2026
497868,497869,NaN,MALE,ASIAN/PACIFIC ISLANDER,NaN,NaN,UNK-UNKNOWN,NaN,NaN,8105435,HONORABLE MENTION,2015-11-09,NaN,FINAL,"HATTULA, CARL",2015-11-03,2015-11-03,NaN,ARUN,ARUN,NACHIMUTHU,NACHIMUTHU,NaN,NaN,NaN,2059
40979,40980,1922.0,MALE,HISPANIC,NaN,1953-04-01,UNK-UNKNOWN,1973-12-16,1985-06-24,8114738,SUPERINTENDENTS AWARD OF VALOR,2017-05-31,HZ239755,DELETED,"DEENIHAN, BRENDAN",2016-04-25,2016-10-10,NaN,AURELIO,AURELIO,GARCIA,GARCIA,NaN,NaN,NaN,2122
40978,40979,1922.0,MALE,HISPANIC,NaN,1953-04-01,UNK-UNKNOWN,1973-12-16,1985-06-24,8113868,HONORABLE MENTION,2017-04-17,JA188581,DELETED,"RIVERA, JORGE",2017-03-15,2017-03-15,NaN,AURELIO,AURELIO,GARCIA,GARCIA,NaN,NaN,NaN,2122
40980,40981,1922.0,MALE,HISPANIC,NaN,1953-04-01,UNK-UNKNOWN,1973-12-16,1985-06-24,8114974,HONORABLE MENTION,2017-06-14,JA237389,DELETED,"ROJAS, JOSE",2017-04-24,2017-04-25,NaN,AURELIO,AURELIO,GARCIA,GARCIA,NaN,NaN,NaN,2122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83227,83228,1957.0,MALE,WHITE,NaN,NaN,UNK-UNKNOWN,NaN,NaN,8094024,DEPARTMENT COMMENDATION,2014-02-12,NaN,DELETED,"LUCKI, JOHN",2007-06-17,2013-07-08,NaN,VOLODIMIR,VOLODIMIR,MINKIN,MINKIN,NaN,NaN,NaN,31717
480609,480610,1957.0,MALE,WHITE,NaN,NaN,UNK-UNKNOWN,NaN,NaN,8099377,UNIT MERITORIOUS PERFORMANCE AWARD,2015-07-01,HW5033239,FINAL,"MASON, THOMAS",2014-07-16,2014-07-17,2017-01-10,VOLODIMIR,VOLODIMIR,MINKIN,MINKIN,NaN,NaN,NaN,31717
83228,83229,1957.0,MALE,WHITE,NaN,NaN,UNK-UNKNOWN,NaN,NaN,8108433,DEPARTMENT COMMENDATION,2016-05-10,HZ118892,DELETED,"GILBERT, TIMOTHY",2016-01-17,2016-02-17,NaN,VOLODIMIR,VOLODIMIR,MINKIN,MINKIN,NaN,NaN,NaN,31717
3142,3143,1930.0,MALE,WHITE,NaN,1956-10-01,UNK-UNKNOWN,1989-07-23,1992-08-16,8093085,MILITARY SERVICE AWARD,2013-12-20,DD-214,DELETED,"OMURO, DAVID",1978-10-28,1980-08-24,NaN,WILLIAM,WILLIAM,ANTONICK,ANTONICK,NaN,NaN,NaN,32043
3140,3141,1930.0,MALE,WHITE,NaN,1956-10-01,UNK-UNKNOWN,1989-07-23,1992-08-16,8040039,HONORABLE MENTION,2008-08-26,HP445131,DELETED,"CALABRESE, WILLIAM",2008-07-10,2008-08-17,NaN,WILLIAM,WILLIAM,ANTONICK,ANTONICK,NaN,NaN,NaN,32043
167640,167641,1930.0,MALE,WHITE,NaN,1956-10-01,UNK-UNKNOWN,1989-07-23,1992-08-16,8051624,COMPLIMENTARY LETTER,2009-03-20,NaN,FINAL,"LEWIS-HALL, KAREN",2008-10-01,2008-10-01,NaN,WILLIAM,WILLIAM,ANTONICK,ANTONICK,NaN,NaN,NaN,32043
3141,3142,1930.0,MALE,WHITE,NaN,1956-10-01,UNK-UNKNOWN,1989-07-23,1992-08-16,8087851,HONORABLE MENTION,2013-03-11,HV348167,DELETED,"DOLAN, DAVID",2013-03-07,2013-03-07,NaN,WILLIAM,WILLIAM,ANTONICK,ANTONICK,NaN,NaN,NaN,32043
11789,11790,NaN,MALE,WHITE,NaN,2003-01-27,UNK-UNKNOWN,NaN,NaN,8072276,HONORABLE MENTION,2011-04-11,NaN,DELETED,"YOUNG, RAY",2011-03-01,2011-03-31,NaN,WILLIAM,WILLIAM,BRATEK,BRATEK,NaN,NaN,NaN,32082
210848,210849,1915.0,MALE,BLACK,NaN,1961-02-20,UNK-UNKNOWN,1975-04-16,1984-07-13,8083247,RECOGNITION / OUTSIDE GOVERNMENTAL AGENCY AWARD,2012-08-02,NaN,FINAL,"HAYNES, DAVID",2012-05-22,2012-05-29,NaN,WILLIAM,WILLIAM,BURKE,BURKE,E,NaN,JR,32095
63642,63643,1940.0,MALE,BLACK,NaN,1993-07-22,UNK-UNKNOWN,NaN,1995-01-01,8068152,DEPARTMENT COMMENDATION,2010-10-19,HR704527,DELETED,"RISLEY, THOMAS",2009-12-24,2009-12-24,NaN,WILLIAM,WILLIAM,KIDD,KIDD,C,NaN,NaN,32307
445491,445492,1926.0,MALE,WHITE,NaN,1948-04-26,UNK-UNKNOWN,1988-02-01,1988-05-01,8073777,COMPLIMENTARY LETTER,2011-06-02,NaN,FINAL,"HOOVER, TRACY",2011-05-18,NaN,NaN,WILLIAM,WILLIAM,MAHONEY,MAHONEY,F,NaN,NaN,32363
515499,515500,1929.0,MALE,WHITE,NaN,1956-05-16,UNK-UNKNOWN,1982-01-01,1986-04-01,8073155,COMPLIMENTARY LETTER,2011-05-11,NaN,FINAL,"HOOVER, TRACY",2010-04-26,NaN,NaN,WILLIAM,WILLIAM,OLSEN,OLSEN,L,NaN,JR,32467
92090,92091,1929.0,MALE,WHITE,NaN,1956-05-16,UNK-UNKNOWN,1982-01-01,1986-04-01,8061499,DEPARTMENT COMMENDATION,2010-01-10,HR679814,DELETED,"BATRICH, RICHARD",2009-12-08,2009-12-08,NaN,WILLIAM,WILLIAM,OLSEN,OLSEN,L,NaN,JR,32467
92091,92092,1929.0,MALE,WHITE,NaN,1956-05-16,UNK-UNKNOWN,1982-01-01,1986-04-01,8088356,HONORABLE MENTION,2013-04-10,HW222742,DELETED,"SCHULER, JOHN",2013-04-07,2013-04-07,NaN,WILLIAM,WILLIAM,OLSEN,OLSEN,L,NaN,JR,32467
92092,92093,1929.0,MALE,WHITE,NaN,1956-05-16,UNK-UNKNOWN,1982-01-01,1986-04-01,8110121,HONORABLE MENTION,2016-09-04,HZ392479,DELETED,"DYCKMAN, JOHN",2016-08-15,2016-08-15,NaN,WILLIAM,WILLIAM,OLSEN,OLSEN,L,NaN,JR,32467
515500,515501,1929.0,MALE,WHITE,NaN,1956-05-16,UNK-UNKNOWN,1982-01-01,1986-04-01,8074687,COMPLIMENTARY LETTER,2011-06-14,NaN,FINAL,"HOOVER, TRACY",2010-11-06,NaN,NaN,WILLIAM,WILLIAM,OLSEN,OLSEN,L,NaN,JR,32467
52271,52272,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8104352,HONORABLE MENTION,2015-08-31,HY403023,DELETED,"STRAND, DONNA",2015-08-30,2015-08-30,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
52272,52273,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8106245,HONORABLE MENTION,2015-12-13,HY512907,DELETED,"KOLASA, MICHAEL",2015-11-24,2015-11-24,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
52270,52271,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8098286,LIFE SAVING AWARD,2014-09-14,HX426225,DELETED,"HANIACEK, JOHN",2014-09-12,2014-09-12,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
52273,52274,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8111736,HONORABLE MENTION,2016-12-16,HZ474933,DELETED,"FREUND, DELON",2016-10-15,2016-12-15,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
52268,52269,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8095547,HONORABLE MENTION,2014-05-20,HX-239509,DELETED,"HENEGHAN, JAMES",2014-04-27,2014-04-27,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
52266,52267,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8088769,HONORABLE MENTION,2013-05-01,HW248505,DELETED,"VERTA, JOHN",2013-04-26,2013-04-26,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
52265,52266,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8086215,HONORABLE MENTION,2012-12-25,HV613824,DELETED,"HEGER, RICHARD",2012-12-23,2012-12-23,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
52264,52265,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8067210,HONORABLE MENTION,2010-09-09,HS497961,DELETED,"CARLI, DENA",2010-09-03,2010-09-03,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
52263,52264,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8066576,HONORABLE MENTION,2010-08-09,HS452990,DELETED,"NAVARRO, KEVIN",2010-08-09,2010-08-09,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
364036,364037,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8098531,COMPLIMENTARY LETTER,2014-09-30,NaN,FINAL,"HOOVER, TRACY",2013-07-10,NaN,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
364035,364036,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8061185,COMPLIMENTARY LETTER,2009-12-28,NaN,FINAL,"LEWIS-HALL, KAREN",2009-07-20,2009-07-20,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
364034,364035,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8056822,COMPLIMENTARY LETTER,2009-07-29,NaN,FINAL,"LEWIS-HALL, KAREN",2009-02-07,2009-02-07,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
52267,52268,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8094208,HONORABLE MENTION,2014-02-23,HX152877,DELETED,"YOUNG, ARTHUR",2014-02-16,2014-02-16,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933
52269,52270,1966.0,FEMALE,WHITE,NaN,2002-06-11,UNK-UNKNOWN,NaN,NaN,8096544,DEPARTMENT COMMENDATION,2014-07-07,NaN,DELETED,"MC CARTHY, JAMES",2014-06-14,2014-06-14,NaN,ANN,ANN,HERR,HERR,M,NaN,NaN,32933

In [102]:
df[df['requester_full_name'] =='MICHALIK, JANE'].award_request_date.value_counts()

2009-05-05    744
2009-07-29     12
2007-10-01     11
2006-08-26      8
2009-09-18      7
2006-11-25      4
2008-01-17      4
2008-03-26      4
2007-09-17      4
2006-04-26      3
2012-05-05      3
2006-05-01      3
2006-11-16      2
2010-09-10      2
2011-04-05      2
2006-09-23      2
2006-06-19      2
2006-06-06      2
2011-05-31      1
2011-03-19      1
Name: award_request_date, dtype: int64

In [ ]:
df

In [3]:
ddf = pd.read_csv('../input/awards_1967-2017_2017-08_profiles.csv.gz')

In [4]:
ddf.head()

,awards_1967-2017_2017-08_ID,first_name,last_name,first_name_NS,last_name_NS,appointed_date,gender,race,middle_initial,middle_initial2,birth_year,current_star,resignation_date
0,13432,JEFFERY,AARON,JEFFERY,AARON,2005-09-26,MALE,WHITE,M,NaN,1971.0,1424.0,NaN
1,16870,KARINA,AARON,KARINA,AARON,2005-09-26,FEMALE,HISPANIC,NaN,NaN,1980.0,20373.0,NaN
2,29448,SUSAN,AARUP,SUSAN,AARUP,2009-01-01,FEMALE,WHITE,J,NaN,1969.0,NaN,2009-02-27
3,1405,ANTHONY,ABBATE,ANTHONY,ABBATE,1994-12-05,MALE,WHITE,G,NaN,1968.0,NaN,2009-12-22
4,3509,CARMEN,ABBATE,CARMEN,ABBATE,1954-10-16,MALE,WHITE,S,NaN,1930.0,NaN,1993-06-04

In [22]:
tt = ddf[ddf['appointed_date'].isnull()]
print(tt.shape)
df[df['awards_1967-2017_2017-08_ID'].isin(tt['awards_1967-2017_2017-08_ID'])][['awards_1967-2017_2017-08_ID', 'current_star', 'rank']].shape
#.drop_duplicates().sort_values('awards_1967-2017_2017-08_ID')

(25, 13)

(34, 3)

In [27]:
tt

,awards_1967-2017_2017-08_ID,first_name,last_name,first_name_NS,last_name_NS,appointed_date,gender,race,middle_initial,middle_initial2,birth_year,current_star,resignation_date
13940,11478,HERBERT,KORDECK,HERBERT,KORDECK,NaN,NaN,NaN,C,NaN,NaN,NaN,NaN
15335,10096,GARY,LORDEN,GARY,LORDEN,NaN,MALE,WHITE,NaN,NaN,1966.0,NaN,NaN
17653,31717,VOLODIMIR,MINKIN,VOLODIMIR,MINKIN,NaN,MALE,WHITE,NaN,NaN,1957.0,NaN,NaN
23892,11011,GROUP,SECURITY,GROUP,SECURITY,NaN,MALE,NaN,NaN,NaN,1975.0,NaN,NaN
29515,29605,SYSTEM,CHRIS,SYSTEM,CHRIS,NaN,NaN,NaN,NaN,NaN,1950.0,NaN,NaN
29928,30043,THOMAS,ANDREWS,THOMAS,ANDREWS,NaN,MALE,HISPANIC,J,NaN,1994.0,NaN,2013-08-14
29938,31167,TRENT,APPLE,TRENT,APPLE,NaN,MALE,NaN,NaN,NaN,1991.0,NaN,NaN
29959,15703,JOSEPH,AUSMANN,JOSEPH,AUSMANN,NaN,MALE,WHITE,C,NaN,1994.0,NaN,2013-08-14
30168,31555,VINCENT,BROWN,VINCENT,BROWN,NaN,MALE,BLACK,NaN,NaN,1953.0,NaN,NaN
30221,3262,CAITLIN,CAIN,CAITLIN,CAIN,NaN,FEMALE,WHITE,M,NaN,1994.0,NaN,2014-06-26
30508,21528,MICHAEL,DEROSA,MICHAEL,DEROSA,NaN,MALE,WHITE,R,NaN,1993.0,NaN,2013-09-12
30811,15878,JOSEPH,GAYDOS,JOSEPH,GAYDOS,NaN,MALE,NaN,NaN,NaN,1985.0,NaN,NaN
30834,5493,DANIEL,GILLESPIE,DANIEL,GILLESPIE,NaN,MALE,WHITE,T,NaN,1994.0,NaN,2013-08-14
31039,13604,JENNIFER,HERNANDEZ,JENNIFER,HERNANDEZ,NaN,FEMALE,HISPANIC,NaN,NaN,1994.0,NaN,2014-01-02
31051,28510,SHARELL,HICKS,SHARELL,HICKS,NaN,FEMALE,BLACK,M,NaN,1994.0,NaN,2014-05-26
31058,28276,SCOTT,HILKERT,SCOTT,HILKERT,NaN,MALE,NaN,NaN,NaN,1970.0,NaN,NaN
31502,4464,CHRISTINA,LOPICCOLO,CHRISTINA,LOPICCOLO,NaN,FEMALE,NaN,NaN,NaN,1952.0,NaN,NaN
31854,2059,ARUN,NACHIMUTHU,ARUN,NACHIMUTHU,NaN,MALE,ASIAN/PACIFIC ISLANDER,NaN,NaN,NaN,NaN,NaN
31968,19354,LUIS,ORTIZ,LUIS,ORTIZ,NaN,MALE,NaN,NaN,NaN,1970.0,NaN,NaN
32024,13864,JESSICA,PAWLAK,JESSICA,PAWLAK,NaN,FEMALE,WHITE,L,NaN,1994.0,NaN,2014-08-29
32124,6342,DAVID,PUPLAVA,DAVID,PUPLAVA,NaN,MALE,NaN,NaN,NaN,1983.0,NaN,NaN
32152,23040,NICHOLAS,RAMIREZ,NICHOLAS,RAMIREZ,NaN,MALE,HISPANIC,A,NaN,1994.0,NaN,2014-05-30
32405,5257,DA' ANGELA,SHEPHERD,DAANGELA,SHEPHERD,NaN,FEMALE,BLACK,M,NaN,1994.0,NaN,2014-03-09
32446,30626,THOMAS,SLAD,THOMAS,SLAD,NaN,MALE,WHITE,E,NaN,1972.0,NaN,NaN
32476,17240,KELLY,SMITH,KELLY,SMITH,NaN,FEMALE,BLACK,M,NaN,1994.0,NaN,NaN

In [26]:
df[df['awards_1967-2017_2017-08_ID'].isin(tt['awards_1967-2017_2017-08_ID'])][['awards_1967-2017_2017-08_ID', 'current_star', 'rank', 'current_award_status', 'award_type']]

,awards_1967-2017_2017-08_ID,current_star,rank,current_award_status,award_type
65552,11478,NaN,UNK-UNKNOWN,DELETED,HONORABLE MENTION
65553,11478,NaN,UNK-UNKNOWN,DELETED,HONORABLE MENTION
65554,11478,NaN,UNK-UNKNOWN,DELETED,DEPARTMENT COMMENDATION
65555,11478,NaN,UNK-UNKNOWN,DELETED,DEPARTMENT COMMENDATION
72150,10096,NaN,UNK-UNKNOWN,DELETED,HONORABLE MENTION
83227,31717,NaN,UNK-UNKNOWN,DELETED,DEPARTMENT COMMENDATION
83228,31717,NaN,UNK-UNKNOWN,DELETED,DEPARTMENT COMMENDATION
112356,11011,NaN,0611-SYSTEMS PROGRAMMER,DELETED,HONORABLE MENTION
140959,29605,NaN,9161-POLICE OFFICER,DENIED,SPECIAL COMMENDATION
166740,30043,NaN,4096-PROGRAM AIDE,FINAL,NATO SUMMIT SERVICE AWARD
168048,31167,NaN,UNK-UNKNOWN,FINAL,HONORABLE MENTION
171512,15703,NaN,4096-PROGRAM AIDE,FINAL,NATO SUMMIT SERVICE AWARD
206716,31555,NaN,UNK-UNKNOWN,FINAL,HONORABLE MENTION
214928,3262,NaN,4096-PROGRAM AIDE,FINAL,NATO SUMMIT SERVICE AWARD
271779,21528,NaN,4096-PROGRAM AIDE,FINAL,NATO SUMMIT SERVICE AWARD
323845,15878,NaN,UNK-UNKNOWN,FINAL,HONORABLE MENTION
327541,5493,NaN,4096-PROGRAM AIDE,FINAL,NATO SUMMIT SERVICE AWARD
362396,13604,NaN,4096-PROGRAM AIDE,FINAL,NATO SUMMIT SERVICE AWARD
366126,28510,NaN,4096-PROGRAM AIDE,FINAL,NATO SUMMIT SERVICE AWARD
366737,28276,NaN,UNK-UNKNOWN,FINAL,HONORABLE MENTION
411522,11478,NaN,UNK-UNKNOWN,FINAL,DEPARTMENT COMMENDATION
411523,11478,NaN,UNK-UNKNOWN,FINAL,HONORABLE MENTION
411524,11478,NaN,UNK-UNKNOWN,FINAL,COMPLIMENTARY LETTER
438575,4464,NaN,UNK-UNKNOWN,FINAL,COMPLIMENTARY LETTER
480579,31717,NaN,UNK-UNKNOWN,FINAL,UNIT MERITORIOUS PERFORMANCE AWARD
497836,2059,NaN,UNK-UNKNOWN,FINAL,HONORABLE MENTION
519528,19354,NaN,UNK-UNKNOWN,FINAL,COMPLIMENTARY LETTER
531119,13864,NaN,4096-PROGRAM AIDE,FINAL,NATO SUMMIT SERVICE AWARD
550398,6342,NaN,UNK-UNKNOWN,FINAL,HONORABLE MENTION
554871,23040,NaN,4096-PROGRAM AIDE,FINAL,NATO SUMMIT SERVICE AWARD
602080,11011,NaN,0611-SYSTEMS PROGRAMMER,FINAL,HONORABLE MENTION
606627,5257,NaN,4096-PROGRAM AIDE,FINAL,NATO SUMMIT SERVICE AWARD
613205,30626,NaN,UNK-UNKNOWN,FINAL,HONORABLE MENTION
616232,17240,NaN,4096-PROGRAM AIDE,FINAL,NATO SUMMIT SERVICE AWARD

In [17]:
ddf[ddf.first_name_NS.str.contains("ISTINA") & ddf.last_name_NS.str.contains("LOPI") & ddf.appointed_date.notnull()]

,awards_1967-2017_2017-08_ID,first_name,last_name,first_name_NS,last_name_NS,appointed_date,gender,race,middle_initial,middle_initial2,birth_year,current_star,resignation_date
15329,4465,CHRISTINA,LOPICCOLO-ROOT,CHRISTINA,LOPICCOLOROOT,2016-06-16,FEMALE,WHITE,R,NaN,1952.0,NaN,NaN

In [12]:
df[df['appointed_date'].isnull()]['rank'].unique()

array(['UNK-UNKNOWN', '0611-SYSTEMS PROGRAMMER', '9161-POLICE OFFICER',
       '4096-PROGRAM AIDE'], dtype=object)